spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_network
    username: postgres
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: "Andre Chamis Social Network"

auth:
  jwt:
    access-token:
      encryption-key: "38f05b12bc0ca4fb5a61514ebf37069b3905b99dd999f6ca1814dabc5bd1bbc9"
      duration: 15
      unit: minutes
    refresh-token:
      encryption-key: "3d8d415f6e71533c37b830c6f93e5de1d8a3275b18e33f52633be458e7a2e050"
      duration: 1
      unit: days
  session:
    duration: 7
    unit: days
  allowed-uris:
    - "/swagger-ui/index.html"
    - "/v3/api-docs"
    - "/v3/api-docs/swagger-config"
  cors:
    allowed-uris:
      - "http://localhost:3000"
