spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_network
    username: postgres
    password: Madebru74
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update